name: Create Production Release
on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: 'Create client release'
    if: github.repository_owner == 'privacyportal' && github.event.repository.name == 'client'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: 'npm ci'
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: 'npm run build -- --mode production'

      - name: Create Tag
        id: create_tag
        uses: butlerlogic/action-autotag@a825539276d173dbaa8d39fb45024d85d292f4f3 # 1.1.2
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          strategy: package
          tag_prefix: 'v'

      - name: Create Release
        if: steps.create_tag.outputs.tagcreated == 'yes'
        run: gh release create ${{ steps.create_tag.outputs.tagname }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Workflow
        if: steps.create_tag.outputs.tagcreated == 'yes'
        run: "gh workflow run client.yml --repo '${{ github.repository_owner }}/client-deployer' --ref production -f ref=${{ steps.create_tag.outputs.tagname }}"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_PERSONAL_ACCESS_TOKEN }}
